### PR TITLE
Use merge-base for comparing lint instead of master

### PR DESCRIPTION
**Pull request by twizmwazin**
Pending testing

### CODE REVIEW

**Comment by rhelmot** [comment]
Can we merge this?

**Comment by twizmwazin** [comment]
I haven't had time to test this yet, if you would like to test or just go for it, we can merge it.

**Comment by rhelmot** [comment]
How can I test it? The script seems to have been tweaked since the last time I looked at it, now it is dependent on the azure filesystem structure.

**Comment by twizmwazin** [comment]
It should work if you build a copy locally and follow the instructions in the readme. If you want to make changes to the repos, just do it between the build step and lint step. If you want to use an existing artifact, I believe you can just extract the tarball in the directory `manual_defaults.sh` leaves you in, and then skip the build step.

**Comment by rhelmot** [comment]
Tested it and fixed a few bugs. It seems to work now.

**Pull request merged**
